git_repo: 'https://github.com/salincandela/ansible-sync-folders-template.git'
git_local_path: '/tmp/ansible_repo/files/'
git_branch: master

#Override this variable
destination_folder: ""

#Insert your regex to filter file to include
include_vars:
 - '--include=*.example'
 #- '--include=*.newfile'
