git_repo: 'https://github.com/salincandela/ansible-sync-folders-template.git'
git_local_path: '/tmp/ansible_repo/files/'
git_branch: master

#Override this variable
destination_folder: ""

dirs_list:
 - "folder_1/folder1_1/"
 - "folder_2/folder_2_1/"

files_list:
 - "folder_1/folder1_1/folder_1_1_2.anotherexample"
 - "folder_2/folder_2_1/folder_2_1_1.example"
 #- "folder_2/folder_2_1/folder_2_1_2.newfile"