  - name: Checkout git folder
    git: repo="{{git_repo}}" dest="{{git_local_path}}"  accept_hostkey=yes force=yes  version="{{git_branch}}"
    delegate_to: localhost

  - name: Clean {{ destination_folder }} path
    file:
      state: absent
      path: "{{ destination_folder }}/"
    #delegate_to: "{{bastion_host}}"

  - name: Setup two lists to be merged
    set_fact:
      init_list:
        - '--prune-empty-dirs'
        - '--include=*/'
      closing_list:
        - '--exclude=*'

  - name: Merge the two lists
    set_fact:
      rsync_filter: "{{ init_list }} + {{ include_vars }} + {{ closing_list }}"


  - name: Synchronize passing in extra rsync options
    synchronize:
      src: "{{git_local_path}}/"
      dest: "{{destination_folder}}/"
      recursive:  yes
      delete: yes
      rsync_opts: "{{rsync_filter}}"
    #delegate_to: "{{bastion_host}}"

  - name: Clean artifact path
    file:
      state: absent
      path: "{{ git_local_path }}/"
    delegate_to: localhost
...
